### ISSUE TITLE
IronSource SDK requires an Activity context to initialize

### ISSUE THREAD

**Issue by ljwan12** [googleads/googleads-mobile-android-mediation#113]
IronSource SDK requires an Activity context to initialize

**Comment by ericleich** [comment]
Correct, [here](https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java#L46) is the line of code where this is checked.

When you create the interstitial or rewarded ad in your app, are you providing the Google Mobile Ads SDK with an activity instead of an application context? This is needed so that we can forward that Activity context to IronSource. There is some documentation on this [here](https://developers.google.com/admob/android/mediation/#initialize_your_ad_object_with_an_activity_instance).
