### ISSUE TITLE
Facebook adapter should not call registerViewForInteraction(view)

### ISSUE THREAD

**Issue by samlu** [googleads/googleads-mobile-android-mediation#14]
Currently FacebookAdapter calls registerViewForInteraction(view) in trackView() which violates FAN policy (No longer allowing "whitespace" of native ads to be clickable).

Please update the code to call registerViewForInteraction(View view, java.util.List<View> clickableViews) instead.

https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookAdapter.java

**Comment by sbagadi** [comment]
Hi @samlu ,

Thanks for bringing this to our attention. We are working on these changes right now.

**Comment by sbagadi** [comment]
A [new version](https://bintray.com/google/mobile-ads-adapters-android/com.google.ads.mediation.facebook/4.25.0.0) which contains the fix for this issue.

Please see the [CHANGELOG](https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/facebook/CHANGELOG.md#42500) for more details.
