### ISSUE TITLE
AdColony  Reward Video onReward doesn't work

### ISSUE THREAD

**Issue by v7lin** [googleads/googleads-mobile-android-mediation#243]
AdColony  Reward Video onReward doesn't work

**Comment by joshuajplagonera** [comment]
Hi All,
Thanks for reporting this issue. I have investigated this issue and can replicate it consistently.

**Comment by pablorengo** [comment]
Hi!
Thanks for taking this issue. Do you think the PR #279 could fix this? This problem happens when not calling MobileAds.initialize(), and calling this method when using AdManager is not mandatory.

**Comment by pablorengo** [comment]
Hi! Any updates on this issue? To workaround this, we have to configure AdColony in Admob even though we are using Google Ad Manager.
It is a **critical** bug, because users are not receiving the reward after watching a 30sec video. And the workaround is error prone for new releases, we have to remind the commercial team to configure AdColony in Admob every time a new app is released.
Thanks!

**Comment by joshuajplagonera** [comment]
Hi @pablorengo ,
Thank you for your patience with regards to this issue.
We released a fix for this issue on the latest version of the AdColony adapter. You can refer to the [CHANGELOG](https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/adcolony/CHANGELOG.md#version-4240) for more information.

Let us know if you are still experiencing this issue with the latest version of the adapter.
