### ISSUE TITLE
AdColony Unexpected SDK version and no Configuration

### ISSUE THREAD

**Issue by jacaTM** [googleads/googleads-mobile-android-mediation#273]
I'm having an issue with AdColony mediation.

First it gives the following log:

"W/AdColonyMediationAdapter( 9479): Unexpected SDK version format: .Returning 0.0.0 for SDK version."

Right after trying to configure it, it returns:

"W/AdColony [WARNING]( 9479): Cannot configure AdColony; configuration mechanism requires 5 seconds between attempts.
W/AdColonyMediationAdapter( 9479): 103: Failed to request ad from AdColony: Not configured
W/AdColonyMediationAdapter( 9479): 103: Failed to configure AdColony SDK."

I'm having 0,15% match rate on AdColony with AdMob mediation, with over 19000 requests and only 22 impressions.

**Comment by ericleich** [comment]
@jacaTM these are 2 unrelated problems.

For SDK version, can you try writing:

    String sdkVersion = AdColony.getSDKVersion();
    Log.d("MyApp", "AdColony SDK version: " + sdkVersion);

and see what comes back? The adapter tries to parse AdColony's SDK version and I'm curious if their SDK version format changed.

Regarding `Cannot configure AdColony; configuration mechanism requires 5 seconds between attempts.`, I can see one optimization we can make to mitigate this error.

**Comment by clevsh** [comment]
Same issue.
----------------------------
String sdkVersion = AdColony.getSDKVersion();
Log.d("MyApp", "AdColony SDK version: " + sdkVersion);
----------------------------
2020-08-08 09:07:55.644 22533-22533 D/MyApp: AdColony SDK version: 

AdColony.getSDKVersion() returns an empty string.

**Comment by RajatVaghani** [comment]
Is there any update on this? Still seeing it :/

**Comment by pchinn** [comment]
@jacaTM  @clevsh  @RajatVaghani  Which AdColony adapter version are you using?
https://bintray.com/google/mobile-ads-adapters-android/com.google.ads.mediation.adcolony/4.2.0.0

>>> "W/AdColony WARNING: Cannot configure AdColony; configuration mechanism requires 5 seconds between attempts.
This is only a warning, and it means the AdColony SDK is getting initialized **more than once** within the last 5 seconds.  The AdColony SDK should be initialized at app launch.

**Comment by RajatVaghani** [comment]
I'm using 4.2.0.0

These are the complete set of logs:

```
W/AdColonyMediationAdapter: Unexpected SDK version format: . Returning 0.0.0 for SDK version.
W/AdColonyMediationAdapter: Unexpected SDK version format: . Returning 0.0.0 for SDK version.
I/AdColony [INFO]: Configuring AdColony
D/MyApp: Adapter name: com.google.ads.mediation.adcolony.AdColonyMediationAdapter, Description: , Latency: 430, State: READY
D/AdNetworkManager: AdColony Version: 4.2.0
W/AdColonyMediationAdapter: 103: Failed to configure AdColony SDK.
W/AdColony [WARNING]: Cannot configure AdColony; configuration mechanism requires 5 seconds between attempts.

```

I could print the version number, shows correctly. But that's it. The failed to configure comes automatically.

**Comment by xfxdev** [comment]
Same problem in 4.2.4.0

```
W/AdColonyMediationAdapter: Unexpected SDK version format: . Returning 0.0.0 for SDK version.
W/AdColonyMediationAdapter: Unexpected SDK version format: . Returning 0.0.0 for SDK version.
W/AdColonyMediationAdapter: Unexpected SDK version format: . Returning 0.0.0 for SDK version.
```

**Comment by ericleich** [comment]
Regarding the `W/AdColony WARNING: Cannot configure AdColony; configuration mechanism requires 5 seconds between attempts.` issue,  commit https://github.com/googleads/googleads-mobile-android-mediation/commit/90ae7d7018ac6d848264a1d6fa0e3e0c037a87ca made it into the 4.2.4.0 release which is that one optimization I mentioned back in August that may fix this. However, please note that if you have any other code in your app that initializes the AdColony SDK that's not Google's AdColony adapter, the issue may still persist. Unfortunately, AdColony SDK doesn't have a way to check if it's been initialized in the past 5 seconds.

Regarding `W/AdColonyMediationAdapter: Unexpected SDK version format: . Returning 0.0.0 for SDK version.`, we've learned that AdColony SDK returns an empty string for `AdColony.getSDKVersion();` until it's been initialized. We found a Google Mobile Ads SDK bug where it's calling getSDKVersion() prior to initializing the AdColony adapter. This will be fixed in a future Google Mobile Ads SDK release, but in the meantime this will just be a benign warning log. I do prefer to keep the log in the adapter as it helped catch this issue in the first place, and was indeed unexpected.

I'm closing this issue as there's nothing else the AdColonyAdapter binary will do to address these logs.
