### ISSUE TITLE
Meta Audience Network Mediation 6.12.0 Native Banner Issue

### ISSUE THREAD

**Issue by appsapiconsole** [googleads/googleads-mobile-android-mediation#434]
On Updating 
Meta Audience Network 
implementation 'com.google.ads.mediation:facebook:6.12.0.0'

Native Banner Configurations not found below things.

import com.google.ads.mediation.facebook.FacebookAdapter
import com.google.ads.mediation.facebook.FacebookExtras

FacebookAdapter::class.java, FacebookExtras()
                                .setNativeBanner(true)
                                .build()
                                
                                
 adLoader.loadAd(
                    AdRequest.Builder()
                        .addNetworkExtrasBundle(
                            FacebookAdapter::class.java, FacebookExtras()
                                .setNativeBanner(true)
                                .build()
                        ).build()
                )

**Comment by joshh-devrel** [comment]
@appsapiconsole 

Since Meta Audience Network no longer serves **waterfall** mediation ad requests (see [Meta's blog post](https://www.facebook.com/audiencenetwork/resources/blog/audience-network-to-become-bidding-only-beginning-with-ios-in-2021)), waterfall integration was removed in [adapter version 6.12.0.0](https://developers.google.com/admob/android/mediation/meta#6.12.0.0). As a result, `FacebookAdapter` and `FacebookExtras` classes were also removed.

As long as you are using a native banner ad placement, the adapter should be able to return a native banner ad. You can also read Meta' documentation on [Native Banner Ads](https://developers.facebook.com/docs/audience-network/setting-up/ad-setup/android/native-banner/).
